# Generated by Django 3.1.7 on 2021-03-20 10:49

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(choices=[('Femme', 'Femme'), ('Homme', 'Homme')], max_length=5, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('adresse', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='user/img')),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField()),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
