# Generated by Django 3.1.7 on 2021-03-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_faq_setting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='subject',
        ),
    ]
