# Generated by Django 3.1.7 on 2021-03-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20210321_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='Ingredients',
        ),
    ]
